### ISSUE TITLE
View.java line 4802

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#56] opened 2018-08-14 17:10 UTC
#### in android.view.View.performClick

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b730d116007d59fcdc81372?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b730d116007d59fcdc81372?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by barreeeiroo** [comment] 2018-08-14 21:16
Duplicate of #42

**Closed as completed by barreeeiroo** 2018-08-14 21:16 UTC
Labels: duplicate
