### ISSUE TITLE
ContainerHelpers.java line 32

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#709] opened 2018-08-27 23:55 UTC
#### in android.util.ContainerHelpers.binarySearch

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b848f8b6007d59fcdff578a?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b848f8b6007d59fcdff578a?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment] 2018-08-28 07:49
This crash is caused by a bug in the Android platform, which was fixed in OS versions > 5. 1. You don’t need to make any changes to your app.

**Closed as completed by michael-winkler** 2018-08-28 07:49 UTC
