### ISSUE TITLE
ActivityThread.java line 2085

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#55] opened 2018-08-14 16:27 UTC
#### in android.app.ActivityThread.performLaunchActivity

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7302f86007d59fcdc7365c?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7302f86007d59fcdc7365c?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by barreeeiroo** [comment] 2018-08-14 21:12
Duplicate of #46

**Closed as completed by barreeeiroo** 2018-08-14 21:12 UTC
Labels: duplicate
