### ISSUE TITLE
View.java line 16469

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#52] opened 2018-08-14 15:28 UTC
#### in android.view.View.getDrawableRenderNode

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72f5216007d59fcdc5efca?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72f5216007d59fcdc5efca?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by barreeeiroo** [comment] 2018-08-14 21:15
Duplicate of #42

**Closed as completed by barreeeiroo** 2018-08-14 21:15 UTC
Labels: duplicate
