### ISSUE TITLE
ClassType.java line 606

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#9] opened 2018-08-12 22:10 UTC
#### in gnu.bytecode.ClassType.addFields

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b70b0596007d59fcd9b9dc1?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b70b0596007d59fcd9b9dc1?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment] 2018-08-14 06:46
@Sander0542 

`Caused by java.lang.ClassNotFoundException: Didn't find class "android.hardware.fingerprint.FingerprintManager$CryptoObject" on path: DexPathList[[zip file "/data/app/io.makeroid.KafaProduction2015.test-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]`

**Comment by Sander0542** [comment] 2018-08-15 13:44
Fixed in https://github.com/Sander0542/Makeroid/pull/388

**Closed as completed** 2018-08-15 13:44 UTC
