### ISSUE TITLE
FusiontablesControl$QueryProcessorV2.onPostExecute(FusiontablesControl.java:982)

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#739] opened 2018-08-28 21:21 UTC
#### in android.view.WindowManagerGlobal.findViewLocked

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b85bce96007d59fcd156da3?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b85bce96007d59fcd156da3?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment] 2018-08-29 06:05
#0. Crashed: main
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:417)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:343)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
       at android.app.Dialog.dismissDialog(Dialog.java:354)
       at android.app.Dialog.dismiss(Dialog.java:337)
       at com.google.appinventor.components.runtime.FusiontablesControl$QueryProcessorV2.onPostExecute(FusiontablesControl.java:982)
       at com.google.appinventor.components.runtime.FusiontablesControl$QueryProcessorV2.onPostExecute(FusiontablesControl.java:794)
       at android.os.AsyncTask.finish(AsyncTask.java:636)
       at android.os.AsyncTask.access$500(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

--

Fatal Exception: java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{1293a6a V.E..... R......D 0,0-684,232} not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:417)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:343)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
       at android.app.Dialog.dismissDialog(Dialog.java:354)
       at android.app.Dialog.dismiss(Dialog.java:337)
       at com.google.appinventor.components.runtime.FusiontablesControl$QueryProcessorV2.onPostExecute(FusiontablesControl.java:982)
       at com.google.appinventor.components.runtime.FusiontablesControl$QueryProcessorV2.onPostExecute(FusiontablesControl.java:794)
       at android.os.AsyncTask.finish(AsyncTask.java:636)
       at android.os.AsyncTask.access$500(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by michael-winkler** [comment] 2018-08-29 06:08
duplicate of https://github.com/Makeroid/BugsTracker/issues/47

**Closed as completed by michael-winkler** 2018-08-29 06:08 UTC
Labels: bug, origin: App Inventor
