### ISSUE TITLE
WindowManagerGlobal.java line 424

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#733] opened 2018-08-28 16:26 UTC
#### in android.view.WindowManagerGlobal.findViewLocked

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b85779a6007d59fcd1083d6?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b85779a6007d59fcd1083d6?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment] 2018-08-29 06:07
duplicate of https://github.com/Makeroid/BugsTracker/issues/739

**Closed as completed by michael-winkler** 2018-08-29 06:07 UTC
Labels: duplicate
