### ISSUE TITLE
Formatter.java line 1111

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#48] opened 2018-08-14 14:00 UTC
#### in java.util.Formatter.getArgument

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72e07c6007d59fcdc3b0f3?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72e07c6007d59fcdc3b0f3?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment] 2018-08-14 14:05
Duplicate of #28

**Closed as completed by michael-winkler** 2018-08-14 14:05 UTC
Labels: duplicate
