### ISSUE TITLE
ActivityThread.java line 3944

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#45] opened 2018-08-14 13:24 UTC
#### in android.app.ActivityThread.deliverResults

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72d81c6007d59fcdc2eb16?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72d81c6007d59fcdc2eb16?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment] 2018-08-14 13:39
`Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.delete()' on a null object reference
       at com.google.appinventor.components.runtime.ImagePicker.copyToExternalStorageAndDeleteSource(ImagePicker.java:188)
       at com.google.appinventor.components.runtime.ImagePicker.saveSelectedImageToExternalStorage(ImagePicker.java:143)
       at com.google.appinventor.components.runtime.ImagePicker.resultReturned(ImagePicker.java:117)`

**Comment by michael-winkler** [comment] 2018-08-14 13:51
Should be fixed in master https://github.com/Sander0542/Makeroid/commit/2cb75f7f7a1fd823830f12f6ace060ea85f0829a

**Closed as completed by michael-winkler** 2018-08-14 13:51 UTC
