### ISSUE TITLE
Download.java line 317

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#40] opened 2018-08-14 12:00 UTC
#### in com.google.appinventor.components.runtime.Download$2.onReceive

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72c46d6007d59fcdc11ff5?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72c46d6007d59fcdc11ff5?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment] 2018-08-14 12:08
`Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=io.mod.ttgfigures (has extras) } in com.google.appinventor.components.runtime.Download$2@f463f6e`

`Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.app.DownloadManager.query(android.app.DownloadManager$Query)' on a null object reference
       at com.google.appinventor.components.runtime.Download$2.onReceive(Download.java:317)`

**Comment by michael-winkler** [comment] 2018-08-14 13:09
Should be fixed in master.

**Closed as completed by michael-winkler** 2018-08-14 13:09 UTC
Labels: bug, origin: Makeroid, priority: Low
