### ISSUE TITLE
ActivityThread.java line 2078

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#23] opened 2018-08-14 06:10 UTC
#### in android.app.ActivityThread.performLaunchActivity

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7272466007d59fcdba8209?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7272466007d59fcdba8209?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment] 2018-08-14 06:34
Same issue like https://github.com/Makeroid/BugsTracker/issues/16

**Comment by barreeeiroo** [comment] 2018-08-14 11:55
Duplicate of #16

**Closed as completed by barreeeiroo** 2018-08-14 11:55 UTC
Labels: duplicate
