### ISSUE TITLE
View.java line 18811

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#54] opened 2018-08-14 16:03 UTC
#### in android.view.View.measure

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72fd426007d59fcdc6b03f?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72fd426007d59fcdc6b03f?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by barreeeiroo** [comment] 2018-08-14 21:16
Duplicate of #42

**Closed as completed by barreeeiroo** 2018-08-14 21:16 UTC
Labels: duplicate
