### ISSUE TITLE
View.java line 6897

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#58] opened 2018-08-14 18:48 UTC
#### in android.view.View.performClick

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7323e76007d59fcdc9d809?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7323e76007d59fcdc9d809?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by barreeeiroo** [comment] 2018-08-14 21:17
Duplicate of #42

**Closed as completed by barreeeiroo** 2018-08-14 21:17 UTC
Labels: duplicate
