### ISSUE TITLE
ActivityThread.java line 2148

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#60] opened 2018-08-14 20:15 UTC
#### in android.app.ActivityThread.performLaunchActivity

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b73384c6007d59fcdcb4f23?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b73384c6007d59fcdcb4f23?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by barreeeiroo** [comment] 2018-08-14 21:13
Duplicate of #46

**Closed as completed by barreeeiroo** 2018-08-14 21:13 UTC
Labels: duplicate
