### ISSUE TITLE
WindowManagerGlobal.java line 401

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#53] opened 2018-08-14 15:39 UTC
#### in android.view.WindowManagerGlobal.findViewLocked

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72f7a06007d59fcdc62cb2?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72f7a06007d59fcdc62cb2?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by barreeeiroo** [comment] 2018-08-14 21:18
Duplicate of #47

**Closed as completed by barreeeiroo** 2018-08-14 21:18 UTC
Labels: duplicate
